[package]
name = "sshcli-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Termius-like desktop GUI for sshcli"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde.workspace = true
sshcli-core = { path = "../core" }
tauri = { version = "2", features = [] }
tokio.workspace = true
